version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - echo "in the install phase"
      - sudo yum update -y
      - sudo yum install -y jq python3-pip python3-devel
      - sudo pip3 install --upgrade awscli
    finally:
      - echo This always runs even if the login command fails 
  pre_build:
    commands:
      - echo "Setting Git Credentials"
  build:
    commands:
       - echo "Build started on $(date)"
       - git clone https://github.com/awslabs/git-secrets
       - cd git-secrets
       - sudo make install
       - cd $CODEBUILD_SRC_DIR
       - git clone https://github.com/darjidhruv26/ResQplate.git
       - cd ResQplate && ls -lrt
       - git secrets --install
       - git secrets --register-aws
       ## Adding additional patterns, for example password
       #- git secrets --add password\s*=\s*.+
       - git secrets --scan --recursive
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  type: zip
  files: '**/*'